### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kocisov** [Kocisov/twchat#1]
### Phase 1
- [ ] Add follower flash message (2s on screen; async)
- [ ] Add Windows TitleBar support
- [ ] Make emoteParser faster and destroy __html

### Phase 2
- [ ] Rethink redux store
